version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: travel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: travel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - travel_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: travel_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@travel.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - travel_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  travel_network:
    driver: bridge
